/**
 * Wraps a cad-gen mesh as a CAD-bench submission: a self-contained Build123D final.py.
 * @remarks CAD-bench (github.com/CAD-bench/cad-bench, MIT) grades a Python file
 *   that leaves a Build123D object in `part`; its verifier tessellates that
 *   object and scores the mesh - dimensions, teeth, thread profiles, a Blender
 *   simulation of gear trains - and five part-aware tasks also read its solids.
 *   cad-gen builds with Manifold, not Build123D, so the bridge embeds cad-gen's
 *   delivered mesh and rebuilds one Build123D solid per body from its
 *   triangles. The grader then scores cad-gen's geometry exactly; what it no
 *   longer sees is authored CAD code, which every report states.
 *
 *   The verifier runs submissions in a sandbox that allows importing only
 *   build123d, math and numpy, with about twenty builtins - no base64, no
 *   struct, no file access - so the mesh travels as plain number lists and
 *   the solids are built with Build123D's own Face / Shell / Solid, which
 *   was verified to rebuild a cube exactly (valid, 8000 mm^3). Each solid is
 *   then clean()ed: with its faces left as hundreds of coplanar triangles,
 *   OCC's booleans failed on it, and CAD-bench's reference gate - which cuts
 *   the part with the reference - read a dimensionally perfect L-bracket as
 *   100% different and scored it 0.
 */

/** Positions closer than this (mm) are the same vertex. */
const WELD_MM = 1e-5;

/**
 * Splits a mesh into its connected bodies.
 * @remarks A gear train arrives as one mesh holding several bodies; CAD-bench's
 *   part-aware tasks need one solid per body, and one Build123D Shell built
 *   from disconnected pieces is not a valid solid. Vertices are welded by
 *   position first, so a triangle soup still splits correctly.
 * @param {{ positions: ArrayLike<number>, indices: ArrayLike<number> }} mesh
 * @returns {{ positions: number[], indices: number[] }[]} Each body re-indexed from zero.
 */
export function bodiesOf(mesh) {
  /** @type {Map<string, number>} */
  const seen = new Map();
  /** @type {number[][]} */
  const unique = [];
  const weld = [];
  for (let i = 0; i < mesh.positions.length / 3; i++) {
    const v = [mesh.positions[i * 3], mesh.positions[i * 3 + 1], mesh.positions[i * 3 + 2]];
    const key = v.map((x) => Math.round(x / WELD_MM)).join(",");
    let id = seen.get(key);
    if (id === undefined) {
      id = unique.length;
      seen.set(key, id);
      unique.push(v);
    }
    weld.push(id);
  }
  const parent = unique.map((_, i) => i);
  /** @param {number} i @returns {number} */
  const find = (i) => {
    while (parent[i] !== i) i = parent[i] = parent[parent[i]];
    return i;
  };
  const tris = [];
  for (let t = 0; t < mesh.indices.length; t += 3) {
    const f = [weld[mesh.indices[t]], weld[mesh.indices[t + 1]], weld[mesh.indices[t + 2]]];
    if (f[0] === f[1] || f[1] === f[2] || f[0] === f[2]) continue;
    tris.push(f);
    parent[find(f[1])] = find(f[0]);
    parent[find(f[2])] = find(f[0]);
  }
  /** @type {Map<number, { positions: number[], indices: number[], local: Map<number, number> }>} */
  const bodies = new Map();
  for (const f of tris) {
    const root = find(f[0]);
    let body = bodies.get(root);
    if (!body) bodies.set(root, (body = { positions: [], indices: [], local: new Map() }));
    for (const v of f) {
      let li = body.local.get(v);
      if (li === undefined) {
        li = body.positions.length / 3;
        body.local.set(v, li);
        body.positions.push(...unique[v]);
      }
      body.indices.push(li);
    }
  }
  return [...bodies.values()].map(({ positions, indices }) => ({ positions, indices }));
}

/** @param {number} v A coordinate, mm. @returns {string} A Python float literal. */
function pyFloat(v) {
  const s = String(Number(v.toFixed(6)));
  return /[.e]/.test(s) ? s : s + ".0";
}

/**
 * The final.py for one task.
 * @param {{ positions: ArrayLike<number>, indices: ArrayLike<number> }} mesh Delivered mesh, mm.
 * @param {{ taskId: string }} meta
 * @returns {string} Python source, valid inside CAD-bench's sandbox.
 */
export function bridgeSource(mesh, meta) {
  const bodies = bodiesOf(mesh).map((b) =>
    "    ([" + b.positions.map(pyFloat).join(", ") + "],\n     [" + b.indices.join(", ") + "]),");
  return `# CAD-bench task ${meta.taskId}: geometry generated by arbesk cad-gen (Manifold kernel),
# embedded as a mesh and rebuilt as one Build123D solid per body for the grader.
from build123d import Face, Shell, Solid, Compound, Vector, Wire

BODIES = [
${bodies.join("\n")}
]


def _solid(points, triangles):
    faces = []
    for k in range(0, len(triangles), 3):
        corners = [Vector(points[3 * v], points[3 * v + 1], points[3 * v + 2]) for v in triangles[k:k + 3]]
        faces.append(Face(Wire.make_polygon(corners, close=True)))
    return Solid(Shell(faces)).clean()


_solids = [_solid(points, triangles) for points, triangles in BODIES]
part = _solids[0] if len(_solids) == 1 else Compound(_solids)
`;
}
